version: 0.2

env:
  shell: bash


phases:
  install:
    commands:
      pip install awscli boto3
  
  build:
    commands:
      - >
        python build_pytorch.py 
        --python-version 3.10
        --pytorch-version 1.13.1
        --is-arm64
        --enable-mkldnn

artifacts:
  files:
    - wheels/*
  discard-paths: yes
  