version: 0.2

env:
  shell: bash

phases:
  install:
    commands:
      - pip install awscli boto3
      - cat ssh_config >> ~/.ssh/config
  
  build:
    commands:
      - >
        python build_pytorch.py 
        --python-version 3.10
        --pytorch-version 2.0.0-rc2

artifacts:
  files:
    - wheels/*
  discard-paths: yes
